-- 智能工作流增量表。chat_run 继续作为取消、会话归属和根 traceId 的权威记录。

CREATE TABLE IF NOT EXISTS intelligent_workflow_run (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    workflow_id VARCHAR(80) NOT NULL,
    workflow_version INT NOT NULL,
    definition_hash CHAR(64) NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    status VARCHAR(40) NOT NULL,
    current_node_id VARCHAR(128) NULL,
    next_sequence BIGINT NOT NULL DEFAULT 1,
    executed_steps INT NOT NULL DEFAULT 0,
    used_tokens BIGINT NOT NULL DEFAULT 0,
    max_steps INT NOT NULL,
    token_budget BIGINT NOT NULL,
    variables_json JSON NULL,
    revision BIGINT NOT NULL DEFAULT 0,
    started_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_iwf_run (tenant_id, run_id),
    KEY idx_iwf_run_workflow (tenant_id, workflow_id, status, id),
    KEY idx_iwf_run_trace (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工作流运行扩展状态';

CREATE TABLE IF NOT EXISTS workflow_node_execution (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    node_execution_id VARCHAR(80) NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    execution_index INT NOT NULL,
    attempt INT NOT NULL DEFAULT 1,
    status VARCHAR(40) NOT NULL,
    display_output MEDIUMTEXT NULL,
    output_json JSON NULL,
    prompt_tokens BIGINT NOT NULL DEFAULT 0,
    candidate_tokens BIGINT NOT NULL DEFAULT 0,
    total_tokens BIGINT NOT NULL DEFAULT 0,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(1000) NULL,
    trace_id VARCHAR(64) NOT NULL,
    started_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wne_id (tenant_id, node_execution_id),
    UNIQUE KEY uk_wne_index (tenant_id, run_id, node_id, execution_index),
    KEY idx_wne_run (tenant_id, run_id, id),
    KEY idx_wne_trace (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工作流节点执行';

CREATE TABLE IF NOT EXISTS workflow_route_decision (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    route_decision_id VARCHAR(80) NOT NULL,
    node_execution_id VARCHAR(80) NOT NULL,
    source_node_id VARCHAR(128) NOT NULL,
    target_node_id VARCHAR(128) NOT NULL,
    edge_id VARCHAR(128) NULL,
    strategy VARCHAR(40) NOT NULL,
    reason VARCHAR(500) NULL,
    terminal TINYINT NOT NULL DEFAULT 0,
    trace_id VARCHAR(64) NOT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wrd_id (tenant_id, route_decision_id),
    UNIQUE KEY uk_wrd_node_execution (tenant_id, run_id, node_execution_id),
    KEY idx_wrd_run (tenant_id, run_id, id),
    KEY idx_wrd_trace (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工作流路由裁决';

CREATE TABLE IF NOT EXISTS workflow_run_event (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    event_id VARCHAR(80) NOT NULL,
    sequence BIGINT NOT NULL,
    schema_version VARCHAR(32) NOT NULL DEFAULT 'workflow-event-v1',
    event_type VARCHAR(64) NOT NULL,
    node_execution_id VARCHAR(80) NULL,
    node_id VARCHAR(128) NULL,
    payload_json JSON NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wre_event (tenant_id, event_id),
    UNIQUE KEY uk_wre_sequence (tenant_id, run_id, sequence),
    KEY idx_wre_replay (tenant_id, run_id, sequence, deleted),
    KEY idx_wre_expire (expires_at, id),
    KEY idx_wre_trace (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='可续传工作流业务事件';

CREATE TABLE IF NOT EXISTS workflow_execution_task (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    task_id VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt INT NOT NULL DEFAULT 0,
    next_retry_at DATETIME(3) NOT NULL,
    lease_owner VARCHAR(128) NULL,
    lease_until DATETIME(3) NULL,
    fencing_token BIGINT NOT NULL DEFAULT 0,
    revision BIGINT NOT NULL DEFAULT 0,
    trace_id VARCHAR(64) NOT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wet_task (tenant_id, task_id),
    UNIQUE KEY uk_wet_idempotency (tenant_id, idempotency_key),
    KEY idx_wet_due (status, next_retry_at, lease_until, id),
    KEY idx_wet_run (tenant_id, run_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工作流可恢复执行任务';

CREATE TABLE IF NOT EXISTS workflow_invocation (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    invocation_id VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    node_execution_id VARCHAR(80) NOT NULL,
    invocation_type VARCHAR(32) NOT NULL,
    replay_class VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    downstream_request_id VARCHAR(128) NULL,
    trace_id VARCHAR(64) NOT NULL,
    started_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wi_invocation (tenant_id, invocation_id),
    UNIQUE KEY uk_wi_idempotency (tenant_id, idempotency_key),
    KEY idx_wi_run (tenant_id, run_id, status, id),
    KEY idx_wi_trace (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工作流外部调用账本';

CREATE TABLE IF NOT EXISTS workflow_outbox (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL,
    outbox_id VARCHAR(80) NOT NULL,
    aggregate_type VARCHAR(40) NOT NULL,
    aggregate_id VARCHAR(80) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload_json JSON NOT NULL,
    status VARCHAR(32) NOT NULL,
    available_at DATETIME(3) NOT NULL,
    lease_owner VARCHAR(128) NULL,
    lease_until DATETIME(3) NULL,
    fencing_token BIGINT NOT NULL DEFAULT 0,
    revision BIGINT NOT NULL DEFAULT 0,
    trace_id VARCHAR(64) NOT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wo_outbox (tenant_id, outbox_id),
    KEY idx_wo_due (status, available_at, lease_until, id),
    KEY idx_wo_aggregate (tenant_id, aggregate_type, aggregate_id, id),
    KEY idx_wo_trace (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能工作流事务消息箱';
