-- 分布式 Multi-Agent 编排：任务账本 + Transactional Outbox。
-- 仅供评审和目标环境变更平台执行；不要在开发机直接连接共享数据库运行。

CREATE TABLE IF NOT EXISTS `agent_subagent_task` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NOT NULL,
  `parent_run_id` VARCHAR(64) NOT NULL,
  `parent_session_id` VARCHAR(64) NOT NULL,
  `parent_agent_id` VARCHAR(128) NOT NULL,
  `task_id` VARCHAR(64) NOT NULL,
  `child_agent_id` VARCHAR(128) NOT NULL,
  `instruction` MEDIUMTEXT NOT NULL,
  `function_call_id` VARCHAR(128) NOT NULL,
  `trace_id` VARCHAR(64) DEFAULT NULL,
  `status` VARCHAR(24) NOT NULL,
  `attempt` INT UNSIGNED NOT NULL DEFAULT 0,
  `fencing_token` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `lease_owner` VARCHAR(128) DEFAULT NULL,
  `lease_expires_at` DATETIME(3) DEFAULT NULL,
  `result_text` MEDIUMTEXT DEFAULT NULL,
  `error_code` VARCHAR(128) DEFAULT NULL,
  `callback_status` VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  `callback_owner` VARCHAR(128) DEFAULT NULL,
  `callback_claimed_at` DATETIME(3) DEFAULT NULL,
  `callback_attempt` INT UNSIGNED NOT NULL DEFAULT 0,
  `callback_last_error` VARCHAR(1000) DEFAULT NULL,
  `callback_delivered_at` DATETIME(3) DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completed_at` DATETIME(3) DEFAULT NULL,
  `acknowledged_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_subagent_task_tenant_task` (`tenant_id`,`task_id`),
  KEY `idx_subagent_function_replay` (`tenant_id`,`parent_run_id`,`function_call_id`,`id`),
  KEY `idx_subagent_parent_inbox` (`tenant_id`,`parent_run_id`,`status`,`id`),
  KEY `idx_subagent_lease_recovery` (`status`,`lease_expires_at`,`id`),
  KEY `idx_subagent_callback` (`callback_status`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='临时子Agent任务与回调账本';

CREATE TABLE IF NOT EXISTS `agent_orchestration_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` VARCHAR(64) NOT NULL,
  `event_id` VARCHAR(64) NOT NULL,
  `event_type` VARCHAR(64) NOT NULL,
  `aggregate_id` VARCHAR(64) NOT NULL,
  `partition_key` VARCHAR(64) NOT NULL,
  `payload` JSON NOT NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `max_attempts` INT UNSIGNED NOT NULL DEFAULT 12,
  `next_attempt_at` DATETIME(3) NOT NULL,
  `lease_owner` VARCHAR(128) DEFAULT NULL,
  `fencing_token` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `lease_expires_at` DATETIME(3) DEFAULT NULL,
  `last_error` VARCHAR(1000) DEFAULT NULL,
  `published_at` DATETIME(3) DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_outbox_event` (`tenant_id`,`event_id`),
  KEY `idx_agent_outbox_due` (`status`,`next_attempt_at`,`id`),
  KEY `idx_agent_outbox_lease` (`status`,`lease_expires_at`,`id`),
  KEY `idx_agent_outbox_aggregate` (`tenant_id`,`aggregate_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent编排Transactional Outbox';
