server:
  port: 8091

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: ${APP_EXECUTOR_CORE_POOL_SIZE:4}
        max-pool-size: ${APP_EXECUTOR_MAX_POOL_SIZE:8}
        keep-alive-time: ${APP_EXECUTOR_KEEP_ALIVE_SECONDS:60}
        block-queue-size: ${APP_EXECUTOR_QUEUE_SIZE:256}
        allow-core-thread-timeout: ${APP_EXECUTOR_ALLOW_CORE_TIMEOUT:true}
        policy: ${APP_EXECUTOR_REJECTION_POLICY:CallerRunsPolicy}

# 日志
logging:
  path: ${OBS_LOG_DIR:./data/log}
  level:
    root: info
  config: classpath:logback-spring.xml
